### ISSUE TITLE
TypeError when application run from /Applications

### ISSUE THREAD

**Issue by forsakendaemon** [CREBP/sra-dedupe-ui#1]
On copying the application to the /Applications folder and attempting to run it, the following error appears. The application runs fine when it's opened from the Downloads folder.

```Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at basename (path.js:1357:5)
    at Command.parse (/Applications/SRA-DeDupe.app/Contents/Resources/app.asar/node_modules/commander/index.js:446:30)
    at Object.<anonymous> (/Applications/SRA-DeDupe.app/Contents/Resources/app.asar/app.js:31:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Object.<anonymous> (/Applications/SRA-DeDupe.app/Contents/Resources/electron.asar/browser/init.js:171:8)```

**Comment by forsakendaemon** [comment]
It looks like this is actually related to opening it for a second time - even opening the .app from ~/Downloads for a second time seems not to work properly.

**Comment by hash-bang** [comment]
@forsakendaemon - Could I grab a bit more info about what you are deploying this on so I can investigate?

Platform, release etc.

**Comment by forsakendaemon** [comment]
Sure! It's the most recent dist version (I downloaded it this morning), being run on Mac OS X 10.12.6 on a 2.9GHz i5 MacBook Pro (Retina, 13", Early 2015) with 16GB of RAM.

 The last step, where you download the files, seems to include the duplicates as well, so I'm thinking that something is very wrong. Do you want me to open a new issue for that?

I'm moving over to the website, but my internet connection is pretty choppy so it's not allowing me to upload as yet, so I can't confirm that that gives a smaller download file.

**Comment by hash-bang** [comment]
@forsakendaemon To be honest I usually do all my dev work on a Linux box so the chances are very high the problem is with me compiling it for a platform I have little knowledge of.

I'll see if I can grab a mac from someone and investigate. In the meantime are you seeing any log output in the console if you run it from there that I could look into?

**Comment by forsakendaemon** [comment]
What's the command that you would use to run from the console on a Linux box?

**Comment by forsakendaemon** [comment]
Okay, if I run SRA-DeDupe.app/Contents/MacOS/SRA-Dedupe without any args, I get the same error. As soon as I add something after that (even `--help` or a nonexistent filename) it starts up normally. I'll run it (with `output.xml` as the argument, which does not exist) and let you know whether that makes any difference to the output.

**Comment by hash-bang** [comment]
Interesting. No idea why its doing that. I'll have to grab a mac and investigate.
